choco install -y "android-sdk";
choco install -y "docker-desktop";
choco install -y "googlechrome" --ignore-checksums;
choco install -y "dotnet-sdk";
choco install -y "flutter";
choco install -y "git" --params "/NoAutoCrlf /WindowsTerminal /NoShellIntegration /SChannel";
choco install -y "gh";
choco install -y "gnuwin32-coreutils.install";
choco install -y "visualstudio2022buildtools";
choco install -y "vscode" --params "/NoDesktopIcon /NoQuicklaunchIcon /NoContextMenuFiles /NoContextMenuFolders";
choco install -y "blender";
choco install -y "epicgameslauncher";
choco install -y "steam";
choco install -y "imagemagick.app";
choco install -y "ffmpeg";
choco install -y "gimp";
choco install -y "krita";
choco install -y "kdenlive";
choco install -y "obs-studio.install";
choco install -y "reaper";
choco install -y "vlc";
choco install -y "wireguard";